import {advanceDistance,headingDifference,largeObstacle} from './ar-core.mjs';

const $=s=>document.querySelector(s);
const params=new URLSearchParams(location.search);
const floor=params.get('floor')||'2f',room=params.get('room')||'205',mobility=params.get('mobility')||'independent';
const floorMeta={b1:['지하 1층','assets/floor-b1.webp'],'1f':['1층','assets/floor-1.webp'],'2f':['2층','assets/floor-2.webp'],'3f':['3층','assets/floor-3.webp']};
const defaultRoutes={b1:[[45,65],[53,63]],'1f':[[45,58],[73,59],[89,49],[92,41]],'2f':[[43,61],[43,66],[52,66]],'3f':[[38,66],[38,78],[24,78],[20,50],[20.5,26]]};
const exitNames={b1:'중앙 비상구','1f':'동북쪽 비상구','2f':'중앙 비상구 2','3f':'서북쪽 비상구'};
const route=parseRoute(params.get('route'))||defaultRoutes[floor]||defaultRoutes['2f'];
const firstVector=[route[1][0]-route[0][0],route[1][1]-route[0][1]],routeBearing=(Math.atan2(firstVector[0],-firstVector[1])*180/Math.PI+360)%360,targetBearing=params.has('bearing')&&Number.isFinite(Number(params.get('bearing')))?Number(params.get('bearing')):routeBearing;
const profiles={wheelchair:{distance:.3,minDelta:.65,maxDelta:4.5,cooldown:520,label:'휠체어 이동'},walkingAid:{distance:.4,minDelta:1.15,maxDelta:6,cooldown:600,label:'보행 보조 이동'},assisted:{distance:.25,minDelta:.9,maxDelta:5,cooldown:750,label:'도움 필요 이동'},independent:{distance:.7,minDelta:1.8,maxDelta:7,cooldown:380,label:'보행 이동'}};
const profile=profiles[mobility]||profiles.independent;
const total=Math.max(1,Math.round(route.slice(1).reduce((sum,p,i)=>sum+Math.hypot(p[0]-route[i][0],p[1]-route[i][1]),0)));
let remaining=Number(params.get('distance'))||total,cameraStream,torch=false,voice=true,signal=false,signalBeep,signalVoice,heading=null,lastMagnitude=0,lastStep=0,model,timer,busy=false,blocked=false,rejected=[];

function parseRoute(value){try{const parsed=JSON.parse(value);return Array.isArray(parsed)&&parsed.length>1?parsed:null}catch{return null}}
function pointAt(percent){const lengths=route.slice(1).map((p,i)=>Math.hypot(p[0]-route[i][0],p[1]-route[i][1])),goal=lengths.reduce((a,b)=>a+b,0)*percent/100;let walked=0;for(let i=0;i<lengths.length;i++){if(walked+lengths[i]>=goal){const t=(goal-walked)/(lengths[i]||1);return[route[i][0]+(route[i+1][0]-route[i][0])*t,route[i][1]+(route[i+1][1]-route[i][1])*t]}walked+=lengths[i]}return route.at(-1)}
function render(){const pct=Math.max(0,Math.min(100,(1-remaining/total)*100)),point=pointAt(pct),points=route.map(p=>p.join(',')).join(' '),meta=floorMeta[floor]||floorMeta['2f'];$('#exitName').textContent=params.get('exit')||exitNames[floor];$('#location').textContent=params.get('location')||`${meta[0]} ${room}호`;$('#distance').textContent=Math.ceil(remaining);$('#mapImage').src=meta[1];$('#mapImage').alt=`${meta[0]} 대피 경로`;$('#mapTitle').textContent=`${meta[0]} ${room} → ${$('#exitName').textContent}`;$('#routeLine').setAttribute('points',points);$('#routeShadow').setAttribute('points',points);$('#exitDot').setAttribute('cx',route.at(-1)[0]);$('#exitDot').setAttribute('cy',route.at(-1)[1]);$('#walker').style.left=`${point[0]}%`;$('#walker').style.top=`${point[1]}%`;$('#progress').textContent=pct>=100?'비상구 도착':pct>0?'대피 이동 중':'출발 지점';$('#remaining').textContent=`전체 ${total}m 중 ${Math.ceil(remaining)}m 남음`;$('#history').textContent=rejected.length?`제외된 경로 ${rejected.length}개`:'제외된 경로 없음';$('#resetButton').disabled=!rejected.length}
function speak(text,force=false){if(!voice||!speechSynthesis)return;const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=.92;if(force)speechSynthesis.cancel();speechSynthesis.speak(u)}
async function selectTorchCamera(){const constraints={width:{ideal:1280},height:{ideal:720}};let first=await navigator.mediaDevices.getUserMedia({video:{...constraints,facingMode:{ideal:'environment'}},audio:false}),track=first.getVideoTracks()[0];if(track.getCapabilities?.().torch)return{stream:first,torch:true,label:track.label};const devices=(await navigator.mediaDevices.enumerateDevices()).filter(device=>device.kind==='videoinput').sort((a,b)=>cameraPriority(b.label)-cameraPriority(a.label));first.getTracks().forEach(item=>item.stop());for(const device of devices){try{const stream=await navigator.mediaDevices.getUserMedia({video:{...constraints,deviceId:{exact:device.deviceId}},audio:false}),candidate=stream.getVideoTracks()[0];if(candidate.getCapabilities?.().torch)return{stream,torch:true,label:candidate.label};stream.getTracks().forEach(item=>item.stop())}catch{}}first=await navigator.mediaDevices.getUserMedia({video:{...constraints,facingMode:{ideal:'environment'}},audio:false});track=first.getVideoTracks()[0];return{stream:first,torch:!!track.getCapabilities?.().torch,label:track.label}}
function cameraPriority(label=''){return/(back|rear|environment|후면|뒷면|wide|광각)/i.test(label)?3:/(front|user|전면|selfie)/i.test(label)?0:1}
async function camera(){try{const selected=await selectTorchCamera();cameraStream=selected.stream;$('#arCamera').srcObject=cameraStream;await $('#arCamera').play();$('#torchButton').disabled=!selected.torch;$('#message').textContent=selected.torch?`손전등 지원 카메라 연결됨${selected.label?` · ${selected.label}`:''}`:'후면 카메라 연결됨 · 손전등 미지원';startVision()}catch(e){$('#message').textContent=e.name==='NotAllowedError'?'카메라 권한을 허용해주세요.':'후면 카메라를 시작할 수 없습니다.'}}
async function sensors(){try{const requests=[];if(typeof DeviceOrientationEvent?.requestPermission==='function')requests.push(DeviceOrientationEvent.requestPermission());if(typeof DeviceMotionEvent?.requestPermission==='function')requests.push(DeviceMotionEvent.requestPermission());if((await Promise.all(requests)).some(x=>x!=='granted'))throw Error();window.addEventListener('deviceorientation',orientation,true);window.addEventListener('devicemotion',motion,true)}catch{$('#message').textContent='브라우저에서 동작 및 방향 센서 권한을 허용해주세요.'}}
function orientation(e){heading=e.webkitCompassHeading??(e.alpha==null?null:360-e.alpha);if(heading==null)return;const rotation=((targetBearing-heading+540)%360)-180,mode=Math.abs(rotation)<45?'forward':rotation>=45&&rotation<135?'right':rotation<=-45&&rotation>-135?'left':'back',labels={forward:'정면',right:'오른쪽',left:'왼쪽',back:'반대 방향'};$('#arrow').className=`arrow ${mode}`;$('#directionCue').textContent=labels[mode];$('#direction').textContent=mode==='forward'?'정면으로 이동하세요':mode==='back'?'반대편으로 돌아서세요':`${labels[mode]}으로 방향을 맞추세요`}
function motion(e){const a=e.accelerationIncludingGravity;if(!a||remaining<=0)return;const magnitude=Math.hypot(a.x||0,a.y||0,a.z||0),delta=Math.abs(magnitude-lastMagnitude),now=Date.now();lastMagnitude=magnitude;if(delta<=profile.minDelta||delta>=profile.maxDelta||now-lastStep<=profile.cooldown)return;lastStep=now;const result=advanceDistance(remaining,{currentHeading:heading,target:targetBearing,step:profile.distance});if(result.reason!=='advanced'){$('#message').textContent=result.reason==='wrong-direction'?'화살표 방향으로 돌아서세요.':'방향 센서를 확인하고 있습니다.';return}remaining=result.distance;$('#message').textContent=blocked?'장애물이 감지되었습니다. 통과 여부를 확인하세요.':`${profile.label} · 올바른 방향으로 이동 중`;render();if(!remaining){$('#direction').textContent='안전한 비상구에 도착했습니다.';speak('안전한 비상구에 도착했습니다. 안내 기능을 계속 유지합니다.',true)}}
async function startVision(){if(!window.cocoSsd){$('#obstacleStatus').textContent='장애물 모델을 불러오지 못했습니다.';return}try{model=await window.cocoSsd.load({base:'lite_mobilenet_v2'});$('#obstacleStatus').textContent='대형 장애물 자동 인식 중';timer=setInterval(detect,1100)}catch{$('#obstacleStatus').textContent='장애물 인식을 시작할 수 없습니다.'}}
async function detect(){const video=$('#arCamera');if(busy||!model||video.readyState<2)return;busy=true;try{const items=await model.detect(video,8,.55),hits=items.filter(x=>largeObstacle(x,video.videoWidth,video.videoHeight));blocked=hits.length>0;$('#arScreen').classList.toggle('blocked',blocked);$('#obstacleStatus').classList.toggle('detected',blocked);$('#obstacleStatus').textContent=blocked?`대형 장애물 감지 · ${Math.round(Math.max(...hits.map(x=>x.score))*100)}%`:'대형 장애물 자동 인식 중';draw(hits)}finally{busy=false}}
function draw(items){const c=$('#obstacleCanvas'),v=$('#arCamera'),ctx=c.getContext('2d');c.width=v.videoWidth||640;c.height=v.videoHeight||480;ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#ff4d57';ctx.lineWidth=5;items.forEach(x=>ctx.strokeRect(...x.bbox))}
function rescue(){navigator.vibrate?.([250,120,250]);const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ac=new AC(),o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime;o.frequency.value=950;g.gain.setValueAtTime(.25,t);g.gain.exponentialRampToValueAtTime(.001,t+.45);o.connect(g).connect(ac.destination);o.start();o.stop(t+.45)}
function stop(){cameraStream?.getTracks().forEach(x=>x.stop());clearInterval(timer);clearInterval(signalBeep);clearInterval(signalVoice);speechSynthesis?.cancel()}

$('#mapButton').onclick=()=>{$('#mapModal').hidden=false;$('#mapButton').classList.add('active');render()};$('#mapClose').onclick=()=>{$('#mapModal').hidden=true;$('#mapButton').classList.remove('active')};$('#mapModal').onclick=e=>{if(e.target===$('#mapModal'))$('#mapClose').click()};$('#torchButton').onclick=async()=>{const track=cameraStream?.getVideoTracks()[0];if(!track)return;try{torch=!torch;await track.applyConstraints({advanced:[{torch}]});$('#torchButton').classList.toggle('active',torch)}catch{$('#message').textContent='이 카메라에서는 손전등을 제어할 수 없습니다.'}};$('#voiceButton').onclick=()=>{voice=!voice;$('#voiceButton').classList.toggle('active',voice);$('#voiceButton').setAttribute('aria-pressed',voice);voice?speak($('#direction').textContent,true):speechSynthesis.cancel()};$('#signalButton').onclick=()=>{signal=!signal;$('#signalButton').classList.toggle('active',signal);$('#arScreen').classList.toggle('signal-active',signal);if(signal){rescue();speak('도움이 필요합니다. 사람이 있습니다.',true);signalBeep=setInterval(rescue,1400);signalVoice=setInterval(()=>speak('도움이 필요합니다. 사람이 있습니다.',true),6000)}else{clearInterval(signalBeep);clearInterval(signalVoice);navigator.vibrate?.(0)}};$('#detourButton').onclick=()=>{rejected.push($('#exitName').textContent);$('#message').textContent='현재 경로를 제외했습니다. 새 경로 데이터가 필요합니다.';render()};$('#resetButton').onclick=()=>{rejected=[];$('#message').textContent='제외한 경로 기록을 초기화했습니다.';render()};addEventListener('pagehide',stop);addEventListener('keydown',e=>{if(e.key==='Escape')$('#mapClose').click()});
render();camera();sensors();
